# Generated by Django 4.2 on 2023-07-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titreDuPoste', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('competences', models.TextField()),
                ('entreprise', models.CharField(max_length=255)),
                ('localisation', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('Ouvert', 'Ouvert'), ('Fermé', 'Fermé')], default='open', max_length=10)),
                ('typeRecrutement', models.CharField(choices=[('Sur site', 'Sur site'), ('A distance', 'A distance'), ('Hybride', 'Hybride')], max_length=15)),
            ],
        ),
    ]
