# Generated by Django 4.1.10 on 2023-08-09 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titreDuPoste', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('competences', models.TextField()),
                ('entreprise', models.CharField(max_length=255)),
                ('localisation', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('Ouvert', 'Ouvert'), ('Fermé', 'Fermé')], default='Ouvert', max_length=10)),
                ('typeEmploi', models.CharField(choices=[('Temporaire', 'Temporaire'), ('Permanent', 'Permanent')], default='Permanent', max_length=15)),
                ('coordinateurs', models.ManyToManyField(blank=True, limit_choices_to={'is_candidat': True}, related_name='coordinateur_offres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
