# Generated by Django 4.1 on 2023-08-10 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='coordinateurs',
        ),
        migrations.AddField(
            model_name='offre',
            name='candidat',
            field=models.ForeignKey(default=1, limit_choices_to={'is_candidat': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
