# Generated by Django 4.2.3 on 2023-07-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='typeRecrutement',
        ),
        migrations.AddField(
            model_name='offre',
            name='typeEmploi',
            field=models.CharField(choices=[('Temporaire', 'Temporaire'), ('Permanent', 'Permanent')], default='Permanent', max_length=15),
        ),
        migrations.AlterField(
            model_name='offre',
            name='statut',
            field=models.CharField(choices=[('Ouvert', 'Ouvert'), ('Fermé', 'Fermé')], default='Ouvert', max_length=10),
        ),
    ]
