# Generated by Django 4.1 on 2023-08-10 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offre', '0003_alter_offre_candidat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='candidat',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
