# Generated by Django 4.1 on 2023-08-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offre', '0004_alter_offre_candidat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offre',
            old_name='candidat',
            new_name='coordinateur',
        ),
    ]
