# Generated by Django 4.1 on 2023-08-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offre', '0006_rename_coordinateur_offre_coordinateur_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offre',
            old_name='coordinateur_id',
            new_name='coordinateur',
        ),
    ]
