# Generated by Django 4.1 on 2023-08-17 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offre', '0007_rename_coordinateur_id_offre_coordinateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('skills', models.TextField()),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offre.offre')),
            ],
        ),
    ]
