# Generated by Django 4.2 on 2023-07-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_customer',
            new_name='is_candidat',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_coordinateur',
        ),
    ]
