# Generated by Django 4.1.10 on 2023-08-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
    ]
