# Generated by Django 4.1.10 on 2023-08-09 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidature', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.TimeField()),
                ('date', models.DateField(blank=True, null=True)),
                ('resultat', models.CharField(choices=[('accepte', 'Accepté'), ('en_attente', 'En attente'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('candidature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='candidature.candidature')),
                ('coordinateur', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
