# Generated by Django 4.1.10 on 2023-08-23 11:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0007_alter_candidature_etat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entretien', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entretien',
            name='heure',
        ),
        migrations.AddField(
            model_name='entretien',
            name='heure_debut',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='entretien',
            name='heure_fin',
            field=models.TimeField(default=datetime.time(12, 30)),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='candidature',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidature.candidature'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='coordinateur',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
