# Generated by Django 4.1.10 on 2023-08-09 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lettre_de_motivation', models.FileField(null=True, upload_to='pdfs/lettresDeMotivation/')),
                ('etat', models.CharField(choices=[('En attente', 'En attente'), ('Rejetée', 'Rejetée'), ('Acceptée', 'Acceptée')], default='En attente', max_length=10)),
                ('candidat', models.ForeignKey(default='', limit_choices_to={'is_candidat': True}, on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to=settings.AUTH_USER_MODEL)),
                ('offre', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='offre.offre')),
            ],
        ),
    ]
