# Generated by Django 4.1.10 on 2023-08-09 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offre', '0001_initial'),
        ('candidature', '0002_alter_candidature_candidat_alter_candidature_offre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='candidat',
            field=models.ForeignKey(default=None, limit_choices_to={'is_candidat': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='offre',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='offre.offre'),
        ),
    ]
