# Generated by Django 4.1.10 on 2023-08-10 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidature', '0004_alter_candidature_candidat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='candidat',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
