# Generated by Django 4.1 on 2023-08-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0005_alter_candidature_candidat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='etat',
            field=models.CharField(choices=[('en attente', 'en attente'), ('rejetée', 'rejetée'), ('acceptée', 'acceptée')], default='En attente', max_length=10),
        ),
    ]
