# Generated by Django 4.1 on 2023-08-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0006_alter_candidature_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='etat',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Rejetée', 'Rejetée'), ('Acceptée', 'Acceptée')], default='En attente', max_length=10),
        ),
    ]
