# Generated by Django 4.1 on 2023-08-29 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0007_alter_candidature_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
